/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import static Controller.BaoHiem_Controller.pstate;
import static Controller.BaoHiem_Controller.sql;
import Controller.Connects;
import static Controller.Luong_controller.pstate;
import static Controller.Luong_controller.sql;
import Controller.NVTV_controller;
import static Controller.NVTV_controller.conn;
import static Controller.NVTV_controller.pstate;
import static Controller.NVTV_controller.sql;
import static QLNS.QLNS.dbUrl;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import models.tblNVTV;
/**
 *
 * @author taihd
 */
public final class BangLuongNVTV extends javax.swing.JInternalFrame {
        boolean ktThem;
        String macu;
        Connects cn = new Connects();
        Date date = new Date();
        DefaultTableModel tbldanhsach;
         public static PreparedStatement pstate;
        List<tblNVTV> arr = new ArrayList<>();
        Calendar calendar = Calendar.getInstance();
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        int currentMonth = Calendar.getInstance().get(Calendar.MONTH);
        int currentDate= Calendar.getInstance().get(Calendar.DATE);
        public static String sql;
    public BangLuongNVTV() throws SQLException {
         initComponents();
         KhoaMo(false);
         XoaTrang();
         cn.loadcombobox(cbMaNV, "select MaNVTV from TblHoSoThuViec", 1);
         tbldanhsach = (DefaultTableModel) TableLuongNVTV.getModel();
        cbMaNV.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED){
                    try {
                        cn.loadtextbox(txtTenPhong, "select * from TblPhongBan b,TblHoSoThuViec a where a.MaPhong=b.MaPhong and MaNVTV='" + cbMaNV.getSelectedItem() + "'", 3);
                    } catch (SQLException ex) {
                        Logger.getLogger(frmCoBan.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
         calendar.set(currentYear , currentMonth , currentDate);
         date.setTime(calendar.getTimeInMillis());
         dateNhanLuong.setDate(date);
        LayNguon();
    }
    
    public void LayNguon(){
        arr = NVTV_controller.LayNguon();
        tbldanhsach.setRowCount(0);
        arr.forEach(p->{
            tbldanhsach.addRow(new Object[]{
                p.getTenphong(),
                p.getManvtv(),
                p.getLuongtv(),
                p.getNgaynhan(),
                p.getNgaycong(),
                p.getNgaynghi(),
                p.getGiolamthem(),
                p.getLuong(),
                p.getGhichu()
            });
        });
    }

    
        public void XoaTrang(){
        txtTenPhong.setText("");
        txtLuongTV.setText("");
        txtGhiChu.setText("");
        txtNgayNghi.setText("");
        txtNgayCong.setText("");
        txtGioLamThem.setText("");
        txtGhiChu.setText("");
        cbMaNV.setSelectedIndex(-1);
        
        calendar.set(currentYear , currentMonth , currentDate);
         date.setTime(calendar.getTimeInMillis());
         dateNhanLuong.setDate(date);
    }
     
    public void KhoaMo(boolean b){
        btnKhong.setEnabled(b);
        btnSua.setEnabled(!b);
        btnThem.setEnabled(!b);
        btnKetThuc.setEnabled(!b);
        btnGhi.setEnabled(b);
        btnTinhLuong.setEnabled(b);
        btnXoa.setEnabled(!b);
        txtTenPhong.setEditable(b);
        txtGioLamThem.setEditable(b);
        txtLuongTV.setEditable(b);
        txtGhiChu.setEditable(b);
        txtNgayCong.setEditable(b);
        txtNgayNghi.setEditable(b);
        dateNhanLuong.setEnabled(b);
        cbMaNV.setEnabled(b);
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        txtTenPhong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNgayNghi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        dateNhanLuong = new com.toedter.calendar.JDateChooser();
        txtGhiChu = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtLuongTV = new javax.swing.JTextField();
        txtTong = new javax.swing.JTextField();
        txtNgayCong = new javax.swing.JTextField();
        txtGioLamThem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableLuongNVTV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnKhong = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        btnTinhLuong = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã NV");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tên phòng");

        cbMaNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaNVItemStateChanged(evt);
            }
        });
        cbMaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMaNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbMaNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbMaNVMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbMaNVMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbMaNVMouseReleased(evt);
            }
        });
        cbMaNV.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cbMaNVInputMethodTextChanged(evt);
            }
        });
        cbMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbMaNVKeyReleased(evt);
            }
        });
        cbMaNV.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cbMaNVVetoableChange(evt);
            }
        });

        txtTenPhong.setEditable(false);
        txtTenPhong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ngày nhận lương");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Số ngày nghỉ");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Số ngày công");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Số giờ làm thêm");

        txtNgayNghi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Ghi chú");
        jLabel17.setToolTipText("");

        dateNhanLuong.setToolTipText("");
        dateNhanLuong.setDateFormatString("yyyy-MM-dd");
        dateNhanLuong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Lương NVTV");

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Tổng");

        txtLuongTV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtTong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTong.setEnabled(false);

        txtNgayCong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtGioLamThem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(jLabel17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLuongTV, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel13)))
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dateNhanLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgayNghi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNgayCong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(txtGhiChu)
                    .addComponent(txtTong))
                .addGap(352, 352, 352))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNgayCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtLuongTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNhanLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 109, 1230, -1));

        TableLuongNVTV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        TableLuongNVTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên phòng", "Mã NVTV", "Lương NVTV", "Ngày nhận lương", "Số ngày nghỉ", "Số ngày công", "Sô giờ làm thêm", "Tổng", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableLuongNVTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableLuongNVTVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableLuongNVTV);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 553, 1230, 405));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        btnSua.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_update_20px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_20px.png"))); // NOI18N
        btnThem.setLabel("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_delete_20px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnGhi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_save_20px.png"))); // NOI18N
        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnKhong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnKhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_no_entry_20px.png"))); // NOI18N
        btnKhong.setText("Không");
        btnKhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhongActionPerformed(evt);
            }
        });

        btnKetThuc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_close_sign_20px.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });

        btnTinhLuong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_stack_of_money_30px.png"))); // NOI18N
        btnTinhLuong.setText("Tính Lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnKhong, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnTinhLuong)
                .addGap(44, 44, 44)
                .addComponent(btnKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 448, 1230, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setText("BẢNG LƯƠNG NHÂN VIÊN THỬ VIỆC");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 671, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void cbMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaNVItemStateChanged

    }//GEN-LAST:event_cbMaNVItemStateChanged

    private void cbMaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMaNVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNVMouseClicked

    private void cbMaNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMaNVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNVMouseEntered

    private void cbMaNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMaNVMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNVMouseExited

    private void cbMaNVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMaNVMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNVMousePressed

    private void cbMaNVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMaNVMouseReleased

    }//GEN-LAST:event_cbMaNVMouseReleased

    private void cbMaNVInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbMaNVInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNVInputMethodTextChanged

    private void cbMaNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbMaNVKeyReleased

    }//GEN-LAST:event_cbMaNVKeyReleased

    private void cbMaNVVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cbMaNVVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNVVetoableChange

    private void TableLuongNVTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableLuongNVTVMouseClicked
        int i = TableLuongNVTV.getSelectedRow();
        txtTenPhong.setText(TableLuongNVTV.getValueAt(i, 0).toString());
        cbMaNV.setSelectedItem(TableLuongNVTV.getValueAt(i, 1).toString());
        txtLuongTV.setText(TableLuongNVTV.getValueAt(i, 2).toString());
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(TableLuongNVTV.getValueAt(i, 3).toString());
            dateNhanLuong.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(frmTangLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNgayCong.setText(TableLuongNVTV.getValueAt(i, 4).toString());
        txtNgayNghi.setText(TableLuongNVTV.getValueAt(i, 5).toString());
        txtGioLamThem.setText(TableLuongNVTV.getValueAt(i, 6).toString());
        txtTong.setText(TableLuongNVTV.getValueAt(i, 7).toString());
        txtGhiChu.setText(TableLuongNVTV.getValueAt(i, 8).toString());
    }//GEN-LAST:event_TableLuongNVTVMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (cbMaNV.getSelectedIndex() == -1){
              return;
         }else if(cbMaNV.getSelectedIndex() > -1){
              macu=cbMaNV.getSelectedItem().toString();
         }
        ktThem=false;
        KhoaMo(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         if(cbMaNV.getSelectedIndex() == -1){
             JOptionPane.showMessageDialog(this, "Không Được Để Trống Mã Nhân Viên","Thông báo", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                int message = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION);
                if(message == JOptionPane.YES_OPTION){ 
                    conn=DriverManager.getConnection(dbUrl);
                    sql="Delete From TblBangCongThuViec Where MaNVTV=?";
                    pstate=conn.prepareStatement(sql);
                    pstate.setString(1, cbMaNV.getSelectedItem().toString());
                    pstate.execute();
                    pstate.close();; conn.close();
                    JOptionPane.showMessageDialog(this, "Xóa thành công!!!","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    DefaultTableModel model = (DefaultTableModel) TableLuongNVTV.getModel();
                    model.setRowCount(0);
                     LayNguon();
                }else{
                    return;
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(frmCoBan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Xóa thất bại!!!","Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        if(ktThem == true){
                        try {
                if(txtLuongTV.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập Lương ","Thông Báo",JOptionPane.WARNING_MESSAGE);
                    return;
                }else if(txtNgayNghi.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập số ngày nghỉ ","Thông Báo",JOptionPane.WARNING_MESSAGE);
                }else if(txtNgayCong.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập số ngày công","Thông Báo",JOptionPane.WARNING_MESSAGE);
                }else if(txtGioLamThem.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập số giờ làm thêm","Thông Báo",JOptionPane.WARNING_MESSAGE);
                }else if(txtTong.getText().length()<=0){
                      JOptionPane.showMessageDialog(this,"Bạn chưa tính lương","Thông Báo",JOptionPane.WARNING_MESSAGE);
                }else{
                    conn=DriverManager.getConnection(dbUrl);
                    sql ="Insert into TblBangCongThuViec(TenPhong,MaNVTV,LuongTViec,"
                    + "NgayNhanLuong,SoNgayCong,SoNgayNghi,SoGioLamThem,Luong,GhiChu)"
                    + " values (?,?,?,?,?,?,?,?,?) ";
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                   pstate = conn.prepareStatement(sql);
                   pstate.setString(1, txtTenPhong.getText());
                   pstate.setString(2,  cbMaNV.getSelectedItem().toString());
                   pstate.setString(3, txtLuongTV.getText());
                   String d = sdf.format(dateNhanLuong.getDate());
                   pstate.setString(4, d);
                   pstate.setString(5,  txtNgayCong.getText());
                   pstate.setString(6, txtNgayNghi.getText());
                   pstate.setString(7, txtGioLamThem.getText());
                   pstate.setString(8, txtTong.getText());
                   pstate.setString(9, txtGhiChu.getText());
                   pstate.execute();
                   conn.close();
                   pstate.close();
                   JOptionPane.showMessageDialog(this, "Thêm thành công!!!","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                   DefaultTableModel model = (DefaultTableModel) TableLuongNVTV.getModel();
                   model.setRowCount(0);
                   LayNguon();
                }

            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this, "Thêm thất bại!!!","Thông báo", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(BangLuong.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
                 if(txtLuongTV.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập Lương ","Thông Báo",JOptionPane.WARNING_MESSAGE);
                    return;
                }else if(txtNgayNghi.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập số ngày nghỉ ","Thông Báo",JOptionPane.WARNING_MESSAGE);
                }else if(txtNgayCong.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập số ngày công","Thông Báo",JOptionPane.WARNING_MESSAGE);
                }else if(txtGioLamThem.getText().length()<=0){
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập số giờ làm thêm","Thông Báo",JOptionPane.WARNING_MESSAGE);
                }else{
                     try {
                         conn=DriverManager.getConnection(dbUrl);
                         sql ="UPDATE TblBangCongThuViec SET TenPhong=?, LuongTViec=?,NgayNhanLuong=?, SoNgayCong=?, SoNgayNghi=?, SoGioLamThem=?, Luong=?, GhiChu=? WHERE MaNVTV=?";
                         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                         pstate = conn.prepareStatement(sql);
                         pstate.setString(1, txtTenPhong.getText());
                         pstate.setString(2, txtLuongTV.getText());
                         String d = sdf.format(dateNhanLuong.getDate());
                         pstate.setString(3,  d);
                         pstate.setString(4, txtNgayCong.getText());
                         pstate.setString(5, txtNgayNghi.getText());
                         pstate.setString(6, txtGioLamThem.getText());
                         pstate.setString(7, txtTong.getText());
                         pstate.setString(8, txtGhiChu.getText());
                         pstate.setString(9, macu);
                         pstate.execute();
                         conn.close();
                         pstate.close();
                          JOptionPane.showMessageDialog(this, "Sửa thành công!!!","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                           DefaultTableModel model = (DefaultTableModel) TableLuongNVTV.getModel();
                           model.setRowCount(0);
                           LayNguon();
                     } catch (SQLException ex) {
                           JOptionPane.showMessageDialog(this, "Sửa thất bại!!!","Thông báo", JOptionPane.ERROR_MESSAGE);
                         Logger.getLogger(BangLuongNVTV.class.getName()).log(Level.SEVERE, null, ex);
                     }
                }
        }
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnKhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhongActionPerformed
        KhoaMo(false);
    }//GEN-LAST:event_btnKhongActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        int exit = JOptionPane.showConfirmDialog(this, "Bạn có muốn kết thúc không?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(exit == JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        int l = Integer.parseInt(txtLuongTV.getText());
        int nc = Integer.parseInt(txtNgayCong.getText());
        int lt = Integer.parseInt(txtGioLamThem.getText());
        float luong = ((l / 26) * nc + (lt * 40000));
        String TongLuong = String.valueOf(luong);
        txtTong.setText(TongLuong);
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ktThem = true;
        KhoaMo(true);
        XoaTrang();
    }//GEN-LAST:event_btnThemActionPerformed

  
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableLuongNVTV;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMaNV;
    private com.toedter.calendar.JDateChooser dateNhanLuong;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGioLamThem;
    private javax.swing.JTextField txtLuongTV;
    private javax.swing.JTextField txtNgayCong;
    private javax.swing.JTextField txtNgayNghi;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
